### ISSUE TITLE
access token renewal via setTimeout not being called when browser tab inactive

### ISSUE THREAD

**Issue by lorenantolik-isti** [Azure-Samples/azure-maps-leaflet#3]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Use anonymous auth type, retrieve access token from Azure Maps via Function App and managed identity service principal.  

Put tab in background.

setTimeout function is not called

azure-maps-leaflet.js line 2097

### Any log messages given by the failure
>

Token Expired

### Expected/desired behavior
>

setTimeout function is called before token expiry.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rbrundritt** [comment]
Odd. The timeout does offset itself to trigger a period of time before the expiry (300ms according to the tokenRefreshClockSkew constant value). Digging into this, it looks like Chrome and Firefox throttle setTimeout in inactive tabs so that they don't fire more than once a second. but the timeout should still fire after that second. Android, however, has a minimum timeout for inactive tabs of 15 minutes which seems crazy. It looks like there might be a workaround to create a timeout inside a web worker. I'll investigate that.

**Comment by rbrundritt** [comment]
Interestingly, I helped someone with an issue around timers and inactive tabs previously and came up with a workaround there that will likely work here: https://stackoverflow.com/questions/72534800/web-audio-when-mobile-screen-turns-off-settimeout-slows-down/72534877#72534877 Going to try adding this into the project today.

**Comment by rbrundritt** [comment]
I have updated the code to support this scenario. It should also work if using the map in a mobile browser and the device lock screen is on.
